# This is a basic workflow to help you get started with Actions

name: action test

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Unit test test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: First log
        run: echo Hello, world!
      - name: Second log
        run: echo Bye
