# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 1.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up exec env
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SENDBIRD_ID: ${{ secrets.SENDBIRD_ID }}
          AGORA_ID: ${{ secrets.AGORA_ID }}
        run: |
          echo "base.url=$BASE_URL" > local.properties
          echo "sendbird.id=$SENDBIRD_ID" >> local.properties
          echo "agora.id=$AGORA_ID" >> local.properties

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Print local properties
        run:
          cat local.properties
      # https://github.com/actions/setup-java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          java-version: ${{ matrix.java }}
      # https://github.com/actions/cache
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Check
        run: ls -al
      # https://github.com/actions/virtual-evironments/tree/master/images/linux
      # 29.0.1 build version 지원하지 않는다
      - name: Run
        run: ./gradlew test --stacktrace

      - name: Build
        run: sudo ./gradlew assemble

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/
        run: ls app/build/outputs/apk/release/

      - name: Send APK to Slack
        run: |
          curl 'https://slack.com/api/files.upload' \
          -H 'Authorization: Bearer ${{ secrets.SLACK_ACCESS_TOKEN }}' \
          -F 'file=@app/build/outputs/apk/release/app.zip' \
          -F "initial_comment=build apk."
          -F channels=G011QBTF8DB

