
name: Build & Upload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up env
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SENDBIRD_ID: ${{ secrets.SENDBIRD_ID }}
          AGORA_ID: ${{ secrets.AGORA_ID }}
        run: |
          echo "base.url=$BASE_URL" > local.properties
          echo "sendbird.id=$SENDBIRD_ID" >> local.properties
          echo "agora.id=$AGORA_ID" >> local.properties

      - name: Print local properties
        run:
          cat local.properties
      # https://github.com/actions/setup-java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          java-version: ${{ matrix.java }}
      # https://github.com/actions/cache
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Check
        run: ls -al

      - name: Run
        run: sudo ./gradlew test --stacktrace

  build:
    name: Build apk
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up env
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SENDBIRD_ID: ${{ secrets.SENDBIRD_ID }}
          AGORA_ID: ${{ secrets.AGORA_ID }}
        run: |
          echo "base.url=$BASE_URL" > local.properties
          echo "sendbird.id=$SENDBIRD_ID" >> local.properties
          echo "agora.id=$AGORA_ID" >> local.properties

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-

      - name: Run
        run: sudo ./gradlew assemble

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author
          author_name: Mike
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#      - name: Upload slack
#        uses: actions/github-slack
#        run: |

